import { describe, expect, test } from "bun:test";
import {
  ouraIntegration,
  whoopIntegration,
  garminIntegration,
  fitbitIntegration,
  withingsIntegration,
  mapmyfitnessIntegration,
  mieleIntegration,
  teslaIntegration,
  tuyaIntegration,
  homeConnectIntegration,
  netatmoIntegration,
  philipsHueIntegration,
  googleHomeIntegration,
  sonosIntegration,
  ringIntegration,
  kickIntegration,
  deezerIntegration,
  uberIntegration,
  amadeusIntegration,
  expediaIntegration,
  eventbriteIntegration,
  meetupIntegration,
  universeIntegration,
  etsyIntegration,
  amazonIntegration,
  bigcommerceIntegration,
  foursquareIntegration,
  uberEatsIntegration,
  wordpressIntegration,
  contentfulIntegration,
  canvasLmsIntegration,
  googleClassroomIntegration,
  microsoftGraphEducationIntegration,
  leverIntegration,
  greenhouseIntegration,
  bamboohrIntegration,
  snowflakeIntegration,
  bigqueryIntegration,
  lookerIntegration,
  tableauIntegration,
  dropboxSignIntegration,
  adobeAcrobatSignIntegration,
  pandadocIntegration,
  metaAdsIntegration,
  microsoftAdsIntegration,
  tiktokBusinessIntegration,
  amazonAdsIntegration,
  moneybirdIntegration,
  exactOnlineIntegration,
  sageIntegration,
  freeagentIntegration,
  oneloginIntegration,
  microsoftEntraIdIntegration,
  dhlIntegration,
  upsIntegration,
  fedexIntegration,
  plaidIntegration,
  truelayerIntegration,
  tinkIntegration,
  gocardlessIntegration,
} from "../../src/index.js";

const cases = [
  [ouraIntegration({ clientId: "id", clientSecret: "secret" }), "oura", "Fitness"],
  [whoopIntegration({ clientId: "id", clientSecret: "secret" }), "whoop", "Fitness"],
  [garminIntegration({ clientId: "id", clientSecret: "secret" }), "garmin", "Fitness"],
  [fitbitIntegration({ clientId: "id", clientSecret: "secret" }), "fitbit", "Fitness"],
  [withingsIntegration({ clientId: "id", clientSecret: "secret" }), "withings", "Fitness"],
  [mapmyfitnessIntegration({ clientId: "id", clientSecret: "secret" }), "mapmyfitness", "Fitness"],
  [mieleIntegration({ clientId: "id", clientSecret: "secret" }), "miele", "Lifestyle"],
  [teslaIntegration({ clientId: "id", clientSecret: "secret" }), "tesla", "Lifestyle"],
  [tuyaIntegration({ clientId: "id", clientSecret: "secret" }), "tuya", "Lifestyle"],
  [homeConnectIntegration({ clientId: "id", clientSecret: "secret" }), "home_connect", "Lifestyle"],
  [netatmoIntegration({ clientId: "id", clientSecret: "secret" }), "netatmo", "Lifestyle"],
  [philipsHueIntegration({ clientId: "id", clientSecret: "secret" }), "philips_hue", "Lifestyle"],
  [googleHomeIntegration({ clientId: "id", clientSecret: "secret" }), "google_home", "Lifestyle"],
  [sonosIntegration({ clientId: "id", clientSecret: "secret" }), "sonos", "Lifestyle"],
  [ringIntegration({ clientId: "id", clientSecret: "secret" }), "ring", "Lifestyle"],
  [kickIntegration({ clientId: "id", clientSecret: "secret" }), "kick", "Entertainment"],
  [deezerIntegration({ clientId: "id", clientSecret: "secret" }), "deezer", "Entertainment"],
  [uberIntegration({ clientId: "id", clientSecret: "secret" }), "uber", "Travel"],
  [amadeusIntegration({ clientId: "id", clientSecret: "secret" }), "amadeus", "Travel"],
  [expediaIntegration({ clientId: "id", clientSecret: "secret" }), "expedia", "Travel"],
  [eventbriteIntegration({ clientId: "id", clientSecret: "secret" }), "eventbrite", "Events & Ticketing"],
  [meetupIntegration({ clientId: "id", clientSecret: "secret" }), "meetup", "Events & Ticketing"],
  [universeIntegration({ clientId: "id", clientSecret: "secret" }), "universe", "Events & Ticketing"],
  [etsyIntegration({ clientId: "id", clientSecret: "secret" }), "etsy", "Commerce"],
  [amazonIntegration({ clientId: "id", clientSecret: "secret" }), "amazon", "Commerce"],
  [bigcommerceIntegration({ clientId: "id", clientSecret: "secret", store_hash: "demo" }), "bigcommerce", "Commerce"],
  [foursquareIntegration({ clientId: "id", clientSecret: "secret" }), "foursquare", "Food"],
  [uberEatsIntegration({ clientId: "id", clientSecret: "secret" }), "uber_eats", "Food"],
  [wordpressIntegration({ clientId: "id", clientSecret: "secret", site: "demo" }), "wordpress", "CMS"],
  [contentfulIntegration({ clientId: "id", clientSecret: "secret" }), "contentful", "CMS"],
  [canvasLmsIntegration({ clientId: "id", clientSecret: "secret", canvas_domain: "demo" }), "canvas_lms", "Education"],
  [googleClassroomIntegration({ clientId: "id", clientSecret: "secret" }), "google_classroom", "Education"],
  [microsoftGraphEducationIntegration({ clientId: "id", clientSecret: "secret" }), "microsoft_graph_education", "Education"],
  [leverIntegration({ clientId: "id", clientSecret: "secret" }), "lever", "HR & Recruiting"],
  [greenhouseIntegration({ clientId: "id", clientSecret: "secret" }), "greenhouse", "HR & Recruiting"],
  [bamboohrIntegration({ clientId: "id", clientSecret: "secret", company_domain: "demo" }), "bamboohr", "HR & Recruiting"],
  [snowflakeIntegration({ clientId: "id", clientSecret: "secret", account: "demo" }), "snowflake", "Data & BI"],
  [bigqueryIntegration({ clientId: "id", clientSecret: "secret" }), "bigquery", "Data & BI"],
  [lookerIntegration({ clientId: "id", clientSecret: "secret", looker_base_url: "demo" }), "looker", "Data & BI"],
  [tableauIntegration({ clientId: "id", clientSecret: "secret", tableau_base_url: "demo" }), "tableau", "Data & BI"],
  [dropboxSignIntegration({ clientId: "id", clientSecret: "secret" }), "dropbox_sign", "Legal"],
  [adobeAcrobatSignIntegration({ clientId: "id", clientSecret: "secret" }), "adobe_acrobat_sign", "Legal"],
  [pandadocIntegration({ clientId: "id", clientSecret: "secret" }), "pandadoc", "Legal"],
  [metaAdsIntegration({ clientId: "id", clientSecret: "secret" }), "meta_ads", "Marketing"],
  [microsoftAdsIntegration({ clientId: "id", clientSecret: "secret" }), "microsoft_ads", "Marketing"],
  [tiktokBusinessIntegration({ clientId: "id", clientSecret: "secret" }), "tiktok_business", "Marketing"],
  [amazonAdsIntegration({ clientId: "id", clientSecret: "secret" }), "amazon_ads", "Marketing"],
  [moneybirdIntegration({ clientId: "id", clientSecret: "secret" }), "moneybird", "Accounting"],
  [exactOnlineIntegration({ clientId: "id", clientSecret: "secret" }), "exact_online", "Accounting"],
  [sageIntegration({ clientId: "id", clientSecret: "secret" }), "sage", "Accounting"],
  [freeagentIntegration({ clientId: "id", clientSecret: "secret" }), "freeagent", "Accounting"],
  [oneloginIntegration({ clientId: "id", clientSecret: "secret", region: "demo" }), "onelogin", "Identity & Access"],
  [microsoftEntraIdIntegration({ clientId: "id", clientSecret: "secret" }), "microsoft_entra_id", "Identity & Access"],
  [dhlIntegration({ clientId: "id", clientSecret: "secret" }), "dhl", "Shipping & Logistics"],
  [upsIntegration({ clientId: "id", clientSecret: "secret" }), "ups", "Shipping & Logistics"],
  [fedexIntegration({ clientId: "id", clientSecret: "secret" }), "fedex", "Shipping & Logistics"],
  [plaidIntegration({ clientId: "id", clientSecret: "secret" }), "plaid", "Banking"],
  [truelayerIntegration({ clientId: "id", clientSecret: "secret" }), "truelayer", "Banking"],
  [tinkIntegration({ clientId: "id", clientSecret: "secret" }), "tink", "Banking"],
  [gocardlessIntegration({ clientId: "id", clientSecret: "secret" }), "gocardless", "Banking"],
] as const;

describe("OAuth expansion integration batch", () => {
  test("creates OAuth integrations with expected ids, categories, and tool lists", () => {
    for (const [integration, id, category] of cases) {
      expect(integration.id).toBe(id);
      expect(integration.oauth?.provider).toBe(id);
      expect(integration.authType).toBe("oauth");
      expect(integration.category).toBe(category);
      expect(integration.description).toBeTruthy();
      expect(integration.tools.length).toBeGreaterThanOrEqual(5);
    }
  });
});
