import { describe, expect, test } from "bun:test";

import * as server from "../../server.ts";

const oauthBatchExports = [
  "googleAdsIntegration",
  "pinterestIntegration",
  "twitchIntegration",
  "xIntegration",
  "ebayIntegration",
  "miroIntegration",
  "smartsheetIntegration",
  "docusignIntegration",
  "pipedriveIntegration",
  "freshserviceIntegration",
  "zohoCrmIntegration",
  "zohoMailIntegration",
  "zohoDeskIntegration",
  "zohoBooksIntegration",
  "zohoProjectsIntegration",
  "zohoCampaignsIntegration",
  "zohoAnalyticsIntegration",
  "zohoInvoiceIntegration",
  "ouraIntegration",
  "whoopIntegration",
  "garminIntegration",
  "fitbitIntegration",
  "withingsIntegration",
  "mapmyfitnessIntegration",
  "mieleIntegration",
  "teslaIntegration",
  "tuyaIntegration",
  "homeConnectIntegration",
  "netatmoIntegration",
  "philipsHueIntegration",
  "googleHomeIntegration",
  "sonosIntegration",
  "ringIntegration",
  "kickIntegration",
  "deezerIntegration",
  "uberIntegration",
  "amadeusIntegration",
  "expediaIntegration",
  "eventbriteIntegration",
  "meetupIntegration",
  "universeIntegration",
  "etsyIntegration",
  "amazonIntegration",
  "bigcommerceIntegration",
  "foursquareIntegration",
  "uberEatsIntegration",
  "wordpressIntegration",
  "contentfulIntegration",
  "canvasLmsIntegration",
  "googleClassroomIntegration",
  "microsoftGraphEducationIntegration",
  "leverIntegration",
  "greenhouseIntegration",
  "bamboohrIntegration",
  "snowflakeIntegration",
  "bigqueryIntegration",
  "lookerIntegration",
  "tableauIntegration",
  "dropboxSignIntegration",
  "adobeAcrobatSignIntegration",
  "pandadocIntegration",
  "metaAdsIntegration",
  "microsoftAdsIntegration",
  "tiktokBusinessIntegration",
  "amazonAdsIntegration",
  "moneybirdIntegration",
  "exactOnlineIntegration",
  "sageIntegration",
  "freeagentIntegration",
  "oneloginIntegration",
  "microsoftEntraIdIntegration",
  "dhlIntegration",
  "upsIntegration",
  "fedexIntegration",
  "plaidIntegration",
  "truelayerIntegration",
  "tinkIntegration",
  "gocardlessIntegration",
] as const;

describe("server entrypoint exports", () => {
  test("exports the OAuth integration batch from integrate-sdk/server", () => {
    for (const exportName of oauthBatchExports) {
      expect(server[exportName]).toBeFunction();
    }
  });
});
