/**
 * Code Mode: sandbox-side runtime stub
 *
 * This file exports a string constant containing the runtime module that gets
 * written into the Vercel Sandbox as `runtime.mjs`. User code imports the
 * `client` from this module and calls `client.<integration>.<method>(args)`.
 * Each call proxies to `POST {INTEGRATE_MCP_URL}` with a Bearer token pulled
 * from `INTEGRATE_SESSION_TOKEN`, reaching the existing `/api/integrate/mcp`
 * route in the host server.
 *
 * The stub is plain ESM that runs under `node22`/`node24` with zero
 * dependencies. It is NOT imported by the host SDK — it only ships as a
 * literal payload to the sandbox.
 */

export const RUNTIME_STUB_SOURCE = /* js */ `// runtime.mjs — generated by integrate-sdk code mode
const MCP_URL = process.env.INTEGRATE_MCP_URL;
const SESSION_TOKEN = process.env.INTEGRATE_SESSION_TOKEN;
const API_KEY = process.env.INTEGRATE_API_KEY || '';
const PROVIDER_TOKENS = process.env.INTEGRATE_PROVIDER_TOKENS || '';
const INTEGRATIONS_HEADER = process.env.INTEGRATE_INTEGRATIONS || '';
const CONTEXT_JSON = process.env.INTEGRATE_CONTEXT || '';

if (!MCP_URL) {
  throw new Error('INTEGRATE_MCP_URL is not set — the sandbox cannot reach the MCP route.');
}

// Diagnostic: log sandbox env summary to stderr so it shows up in the
// execute_code result's stderr field for debugging auth issues.
console.error('[sandbox-diag] MCP_URL=' + MCP_URL);
console.error('[sandbox-diag] HAS_API_KEY=' + !!API_KEY);
console.error('[sandbox-diag] HAS_SESSION_TOKEN=' + !!SESSION_TOKEN);
console.error('[sandbox-diag] HAS_PROVIDER_TOKENS=' + !!PROVIDER_TOKENS);
if (PROVIDER_TOKENS) {
  try {
    const _parsed = JSON.parse(PROVIDER_TOKENS);
    const _keys = Object.keys(_parsed);
    console.error('[sandbox-diag] PROVIDER_TOKEN_KEYS=' + _keys.join(','));
    console.error('[sandbox-diag] TOKEN_LENGTHS=' + _keys.map(k => k + ':' + (typeof _parsed[k] === 'string' ? _parsed[k].length : typeof _parsed[k])).join(','));
  } catch { console.error('[sandbox-diag] PROVIDER_TOKENS is not valid JSON'); }
}

function camelToSnake(str) {
  return str.replace(/[A-Z]/g, (letter) => '_' + letter.toLowerCase());
}

async function callTool(toolName, args) {
  const headers = {
    'Content-Type': 'application/json',
    'x-integrate-code-mode': '1',
  };
  if (SESSION_TOKEN) headers['Authorization'] = 'Bearer ' + SESSION_TOKEN;
  if (API_KEY) headers['x-integrate-api-key'] = API_KEY;
  if (PROVIDER_TOKENS) headers['x-integrate-tokens'] = PROVIDER_TOKENS;
  if (INTEGRATIONS_HEADER) headers['x-integrations'] = INTEGRATIONS_HEADER;
  if (CONTEXT_JSON) headers['x-integrate-context'] = CONTEXT_JSON;

  console.error('[sandbox-diag] callTool: ' + toolName + ' → ' + MCP_URL);
  console.error('[sandbox-diag] headers: ' + JSON.stringify({
    hasAuth: !!headers['Authorization'],
    hasApiKey: !!headers['x-integrate-api-key'],
    hasTokens: !!headers['x-integrate-tokens'],
    hasCodeMode: !!headers['x-integrate-code-mode'],
  }));

  const res = await fetch(MCP_URL, {
    method: 'POST',
    headers,
    body: JSON.stringify({ name: toolName, arguments: args || {} }),
  });

  const text = await res.text();
  console.error('[sandbox-diag] response: HTTP ' + res.status + ' len=' + text.length);

  let payload;
  try {
    payload = text ? JSON.parse(text) : null;
  } catch {
    payload = { content: [{ type: 'text', text }] };
  }

  if (!res.ok) {
    let message = (payload && (payload.error || payload.message)) || 'Tool call failed: HTTP ' + res.status;
    if ((res.status === 401 || res.status === 403) && typeof text === 'string' && text.indexOf('Authorization header') !== -1) {
      message =
        'Code Mode callback was rejected by the MCP server (HTTP ' + res.status + '). ' +
        'The SDK route could not synthesize an Authorization header. Check the host-side ' +
        'createMCPServer config (apiKey, getProviderToken) or pass providerTokens to the ' +
        'AI helper. Original upstream message: ' + text;
    }
    const err = new Error(message);
    err.status = res.status;
    err.toolName = toolName;
    throw err;
  }

  return payload;
}

function createIntegrationProxy(integrationId) {
  return new Proxy({}, {
    get(_target, methodName) {
      if (typeof methodName !== 'string') return undefined;
      return (args) => callTool(integrationId + '_' + camelToSnake(methodName), args);
    },
  });
}

export const client = new Proxy({}, {
  get(_target, integrationId) {
    if (typeof integrationId !== 'string') return undefined;
    return createIntegrationProxy(integrationId);
  },
});

export { callTool };
`;
